[package]
name = "efw"
description = "Framework for writing UEFI applications"
version = "0.0.0"
authors = ["Richard Wiedenhöft <richard@wiedenhoeft.xyz>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/richard-w/efw"

[lib]
path = "src/lib.rs"
test = false

[dependencies]
late-static = "0.3"
r-efi = { git="https://github.com/richard-w/r-efi", branch="graphics-output-protocol" }
ucs2 = "0.1"
