name: ci

on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install nightly toolchain
        run: rustup toolchain install nightly

      - name: Install rust sources
        run: rustup component add --toolchain nightly rust-src

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: cargo build --target x86_64-unknown-uefi

      - name: Run Tests
        run: cargo test -Z build-std=std --target x86_64-unknown-linux-gnu

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Install nightly toolchain
        run: rustup toolchain install nightly

      - name: Install rust sources
        run: rustup component add --toolchain nightly rust-src

      - name: Install clippy for nightly
        run: rustup component add --toolchain nightly clippy

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run clippy
        run: cargo clippy --verbose --all --target x86_64-unknown-uefi

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check formatting
        run: cargo +stable fmt --all -- --check
