name: CI

on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install cargo-xbuild 
        run: cargo install cargo-xbuild

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: cargo xbuild --target x86_64-unknown-uefi

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run clippy
        run: cargo clippy --verbose --all

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check formatting
        run: cargo fmt --all -- --check
